### ISSUE TITLE
[Font-weight] Add new font-weight

### ISSUE THREAD

**Issue by h22y25n** [cloudforet-io/mirinae#124]
**Problem**
Need new font weight (between regular and blod)

**Solution**
Add medium(500) font weight

**Figma / Jira Link**
[Typography](https://www.figma.com/file/DVwz3WQLLIxWXj4d4W8MQI/Foundation?node-id=17863%3A182708&viewport=6928%2C1468%2C0.44)

**Comment by song2kim** [comment]
Medium font-weight was also added to the [console](https://github.com/cloudforet-io/console/pull/280).
