### ISSUE TITLE
[sidebar] Update a width prop

### ISSUE THREAD

**Issue by h22y25n** [cloudforet-io/mirinae#241]
**Problem**
lg, md size sidbar has a percentage width. but we need a fixed width sidebar.

**Solution**
Add a `fixed-width` prop,
so we can use percentage width and fixed width also.
 |         | percentage |       px(rem) |
 |----- |------------ |---------- |
| lg    |  30%            |  400px(25) |
 |  md |  25%            |  320px (20)|
 |  sm  |  20%            |  260px (16.25)|

**Figma / Jira Link**
[Go to Figma](https://www.figma.com/file/IS6P8y1Wn2nfBC4jGlSiya/Components?node-id=10%3A228508&t=WCtkH9L66MGcj8Tg-11)

**Comment by song2kim** [comment]
How about naming the props `isFixedSize`?

**Comment by h22y25n** [comment]
`isFixedSize` is LGTM!!! ☺️

**Comment by song2kim** [comment]
`400px(18.75rem)` should be changed `400px(25rem)`😀
