### ISSUE TITLE
[Dynamic Layout > item, Dynamic Field > dict][Definition Table] Display objects and arrays more user friendly

### ISSUE THREAD

**Issue by WANZARGEN** [cloudforet-io/mirinae#33]
**Is your feature request related to a problem? Please describe.**
object, array data was not readable.
<img width="549" alt="image" src="https://user-images.githubusercontent.com/26986739/192194926-0638ace9-74be-4d9f-92a1-9808303ef0ff.png">

**Describe the solution you'd like**
Display `object` data with Dict component. (Not developed yet.)
Display `array` data with TextList component. (It's console component now, but must be moved as mirinae component)

**Describe alternatives you've considered**

**Additional context**
Dict component is not developed yet. Must be developed after [this issue](https://github.com/cloudforet-io/mirinae/issues/32).

**Comment by piggggggggy** [comment]
This issue has beeb resolved.

**Comment by piggggggggy** [comment]
This issue has beeb resolved.
