### ISSUE TITLE
[select-card] Update

### ISSUE THREAD

**Issue by dsict** [cloudforet-io/mirinae#75]
**Problem**
No content flexibility

**Solution**
Add Slot

**Figma / Jira Link**
https://www.figma.com/file/IS6P8y1Wn2nfBC4jGlSiya/Components?node-id=10%3A199445

**Additional Description**
- Add focused state design for keyboard usability
   (must be selectable by using keyboard)

**Comment by minseolee** [comment]
It has been merged #85 
Closing this issue.
